sudo: false
dist: trusty
language: python
addons:
  apt:
    packages:
    - python3
python:
- '3.6'
install:
- pip install -r requirements.txt
services:
- docker
env:
  global:
  - DOCKER_REGISTRY=reveller
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: DANQUauuSs8VuWO9UxN7I6PdAQlTc3TZubmJ/YzxU9Uk67ZlhLUP2qoJbxJ/2cIR+4y3uwqJ0o1O+BwIjeukzQz5CnRbefUjLUWkFL266EF05nlE2Pwwq2TF2kTmba4ZdmPWTbLm33YLqKRTOhRAWBJblw2bNZ8ndCEQQsvy3c+94z+wIzk/guzN0CzuVKf9KpqzyOaWi1vIiUbVfpeuDBccuLwC6O2PUJTBWCuJ+l27eQV4bZ+uX1CPg7b4JvJLVL/y14x8MeCtmnLXyuYfeMQRF9eQA/OG3JL+/l0QO7inhFZEu6Cqbuz0UJMEFmzrdZhvnlfXaj907/oqdCFr19J5BK8p9Sr/+dz6cxB0BQcAvoD47cX8D1MAj7xZdzrbtL+H/HkZ/FWRw3twgvpDjeFqUOWXeqcp/XLwr1fJ6i41PnaUz3v62WVpOfdTrdqIo3puHm0Sph2hxXVEGnfBLNaeoKT0wQbt0ykg8nFYxLxPfrKv5Upu6wxFoUpQCXdyBt8jDMKxHSFxH18nVqXYqL9oLdfHhVR0TmT/7Wx2T0q9POxNNXS0tCNCD/+CBy0/7iqkF3bnVb6i+J140+M83hXVmsxfabV13XgKt+qP6M9sJx7EPXDxSG+woe1F+cTe/4UHZgmK9n9FmBRkbkVO/qfpGO2NlK95msm13Er3qmM=
  - secure: IGYK+xBoK7bBlxJByMUzx67yM4a7cb0/5Q038oVnfxdRPDkBUp6lbqR7djiKYuBocL2NqsGJBms5ArYXAhalfZLobhvzIeOv41CVdTUycOXXQwxJogHuOAWKC7FDCk0Uo7ijPmB5gyzZlYbwEVc93WXm0wF7FcUPXkRZE/U8iNe75szKVQPvMkqClvMl5I6GSi2bYQ6xwiZthlZGhJ1mwjKmM/Il16a0nSXEfDMBaWi6DQDy9GuOF1m1eteECXKtc9GO1TUQOvz/VaXz/vn3uaegJctZpBmRVp7i0a8wM3XfYPRtu+at2m/kDpPToWI4u/RbKavRwDgCbWilJ9R4PrpiGuAW2es5P1RYmAAymaH8d2uSjrpaJnjYd23FHtIlgb7z17uTje1K0MlXBY8JFN0VUFR1Taqtbf2V+66ntVL5RvS8x2Rl5xpvyk4h6QZtX1U1PRMPWylTr/QLH9FLIAj7+6iCRXJfaZo5w7KdhDNeM2Zzwdc7hGgbMk7DJXKX85nOqdaW9DpM41apxt+SrTsDb/7S0U1b15+U88x1hShfmOx7H7aLqVriW9NTYEoXcuq+O+IuMVquVZEO5vSPmV8Fkvtqav5JwFbx+kXMEK3ccqx0wyyM6bNJ+wpfwnLGvhOLTyzIfFEfIu+Be7mIPE3WmtixIbNhK1Be2MhCFZc=
  - secure: WI4vUBz+lvZa9ZdpEciYHIcfumepQjECfghyAtv/47nhaTi2wv+4KGYwU3fIBxDXgxJZjhR854yxEnYw+dEnyyLIzqK6K+BFdXAD2GMfARioLyere6HTb6TCzxWGL9KGVp7P113AgNKXwRSO+jmpZqBcqevmN7NZzeUrhluRTOdM/Nh2w9xbQkVhCMJEI3aTrZsO1ys82a/aXy2MVFP+GBal9IH9boXe0ltNBLdMSKBnv4d58/XOzvfs3VfIrA4PcOwzYGPcc0Q6vpuu0osU0UEP2rywKQQz+hVRsTsYCDRgwP+416FLRzgsCoQlg1PzmCP8RGKJhAmy+pyQK/5JQBB9AtglUkp+BqluXUNg2y198yIzsFmxze2IyghuBJwMz0Z7vEDBKZEUpeAKepJzFY/0Mk1EcU7lmnsygmZeNMVSuihaffdv0caoxndQDJ3cwOLbZPxtc3X6Lhq89CQtHNMxpvMM88d3vsO9Vq2NFe5grCRdiwOmdo9caNZVpLz7KvaSJVqSxYI7VbfNwJKYXinaw5cK4v+0KymKsK7FikPCrhVLt5j1cO1+qrEbmu8UkJpAdPFE09hYiS16m76XHWBu1oMULiEd2dqWRgefuwIR94T2ttld4TzAkc6pZIXqKztmuR9b1pNT7MYwwPGUGhCpfYvKSAV+8mT31L7SBpw=
script:
- bash travis-build.sh
