sudo: false
dist: trusty
language: python
addons:
  apt:
    packages:
    - python3
python:
- '3.6'
install:
- pip install -r requirements.txt
services:
- docker
env:
  global:
  - DOCKER_REGISTRY=reveller
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: DANQUauuSs8VuWO9UxN7I6PdAQlTc3TZubmJ/YzxU9Uk67ZlhLUP2qoJbxJ/2cIR+4y3uwqJ0o1O+BwIjeukzQz5CnRbefUjLUWkFL266EF05nlE2Pwwq2TF2kTmba4ZdmPWTbLm33YLqKRTOhRAWBJblw2bNZ8ndCEQQsvy3c+94z+wIzk/guzN0CzuVKf9KpqzyOaWi1vIiUbVfpeuDBccuLwC6O2PUJTBWCuJ+l27eQV4bZ+uX1CPg7b4JvJLVL/y14x8MeCtmnLXyuYfeMQRF9eQA/OG3JL+/l0QO7inhFZEu6Cqbuz0UJMEFmzrdZhvnlfXaj907/oqdCFr19J5BK8p9Sr/+dz6cxB0BQcAvoD47cX8D1MAj7xZdzrbtL+H/HkZ/FWRw3twgvpDjeFqUOWXeqcp/XLwr1fJ6i41PnaUz3v62WVpOfdTrdqIo3puHm0Sph2hxXVEGnfBLNaeoKT0wQbt0ykg8nFYxLxPfrKv5Upu6wxFoUpQCXdyBt8jDMKxHSFxH18nVqXYqL9oLdfHhVR0TmT/7Wx2T0q9POxNNXS0tCNCD/+CBy0/7iqkF3bnVb6i+J140+M83hXVmsxfabV13XgKt+qP6M9sJx7EPXDxSG+woe1F+cTe/4UHZgmK9n9FmBRkbkVO/qfpGO2NlK95msm13Er3qmM=
  - secure: ZDbusPr1n26xLknxkt+C3X+EwgSGT00Ef++ivhOp2MriU07YlMScgLA2aBQVVQhqXiNtmxF8EK8fSayhRTSKY5+TRxtXznUZZ2VAXcylx5z6CKAd6zAAjTLUDB7/5Q9Xiwbdy9V8kTGsHW2Fci1XI1zUvo66RMviGsuBy/5DN5QR669krue6guwa77tmMiaRq2VUnqIFi5e3ljx8Qk00QbOixPnd6HthXPPL4JPe50LP44KZxE/bdUFiZ0YKp21wPtBb2bvg99yPJPC8chl0EpUtVJEunBBECxN980vssltjaIwh3vyqt68pVK4gnq0ULnCajZVWdXMzdn2uJyo1Ble89VR7Xpxv5WEkm7my0exFHQSZkuUZQx69B6QD/IlrW96sEB3KyNvYGpaTX2LCwt4QwLq6WYCrG3HExewMCOvptDGwpjqHexMXTbDWytSGog+7Mrr5tf4fD4DW6AInKD2PI59AHhpHKQ046ry0LsvgJaZX+feY2Vuq/UaeCcWd6RPuaG2ZSiaDTZEpPp8Gw58OK3w6DVt9PI9y5k6yxGIcloMPQfJyTx5CNZEQ2E7HCgKVbyJ9Po67Tnc2QuwooWwe7lDV8opDbIgEJICZo1kBuC+EMMa5IPK4kJ5kUTWA2ccLZYC2tBHdg8q8dvejGmnriBS0SG3pyfxhJj2RmAo=
  - secure: pwQL0IUbJkVAkyK4eGoaCy/88jpcfQmPFXxEWcRw5hbU0XAZMfHlnenhPvA0gQbjMQYCrXVr5cW/+jIiiF9bXnfQOW8b0aiLXWGYvfNBqGDblRykatJBPgBpzv1/CrMfJ7V5J07CwQ0Ky3iJeeW+NBPyvMTNuvSmPe98B3HLbDCCiJfpwD8L4070n9KK3X3RjBoRNalA9SJefosH/xN9DEsHD5ePSLNaDjEMyHwR/3OueRhdrvi5NS+2F+18T3lXDh/rOCDhdKz+aW9MCws40/ZQ2QVoThVxMi0CI2L35OZ+cuqxrYI20T4FkyPrt/cr/Ab55bbgFBeUOryrTyKNd+VJB3d09tQT3nADBP8p3xQgxutjnj81CI7Ek0ulc8ktmLMK7WnTkf2/KMy+48y3idbTpdDrP0ortxRXJZ3quzRmk3RdE/0Z3oOxPQLVZK+/oCH7IKDIPCLbU1IZgFwIOBErCYQaVuAIVFTRDZQAM+fcaEcTn9AZwJh6tf6EbXpgfZig3j8y/aIYNzY8RnXngj9JtC5fBFunvVOZxRqvo0lpwbFhrUNKSacOXKZ8jaGR+GM9fd5xXCuZEs3OyZufwGwL+Vy5QppXlRuSpP9K3wWRempq63u5LME7EAgfQEzJ+xN64F0haVGd345dN3NUpHgAJzTp7UQ5MoppdKg8cW8=
script:
- bash travis-build.sh
