sudo: false
dist: trusty
language: python
addons:
  apt:
    packages:
    - python3
python:
- '3.6'
install:
- pip install -r requirements.txt
services:
- docker
env:
  global:
  - DOCKER_REGISTRY=reveller
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: DANQUauuSs8VuWO9UxN7I6PdAQlTc3TZubmJ/YzxU9Uk67ZlhLUP2qoJbxJ/2cIR+4y3uwqJ0o1O+BwIjeukzQz5CnRbefUjLUWkFL266EF05nlE2Pwwq2TF2kTmba4ZdmPWTbLm33YLqKRTOhRAWBJblw2bNZ8ndCEQQsvy3c+94z+wIzk/guzN0CzuVKf9KpqzyOaWi1vIiUbVfpeuDBccuLwC6O2PUJTBWCuJ+l27eQV4bZ+uX1CPg7b4JvJLVL/y14x8MeCtmnLXyuYfeMQRF9eQA/OG3JL+/l0QO7inhFZEu6Cqbuz0UJMEFmzrdZhvnlfXaj907/oqdCFr19J5BK8p9Sr/+dz6cxB0BQcAvoD47cX8D1MAj7xZdzrbtL+H/HkZ/FWRw3twgvpDjeFqUOWXeqcp/XLwr1fJ6i41PnaUz3v62WVpOfdTrdqIo3puHm0Sph2hxXVEGnfBLNaeoKT0wQbt0ykg8nFYxLxPfrKv5Upu6wxFoUpQCXdyBt8jDMKxHSFxH18nVqXYqL9oLdfHhVR0TmT/7Wx2T0q9POxNNXS0tCNCD/+CBy0/7iqkF3bnVb6i+J140+M83hXVmsxfabV13XgKt+qP6M9sJx7EPXDxSG+woe1F+cTe/4UHZgmK9n9FmBRkbkVO/qfpGO2NlK95msm13Er3qmM=
  - secure: ZFY3XsxUoqjWTNcKx/aLOJNpqQmaUcm40FHyna23AJwZ2FWKx5KMssdpGk/cmqRlMm7e44/98FREAtFuy29DrEGUbD7OB97O/DM+OGeHMbsJ1EnXHOzO7v6KG0MgS08DYS4pGAbs2aJkpsGt7PDE7tss9dzc1P7jUsJ0RmoR+Ap7KpXALgYlS7j9P2JISOVqEA/d00DyXtIQc3bK0z4mJgrv5gfLctynUaHzET5N5b2szTlas1hLOCfwrdtYn15CSuc9Q8/AblBPI7Rp+xMHBQ2h8uvCMb5cut1ertjLQqLFYvOUSkRni/j0tBPHvXjrvS3KvYxCZUpgI1H3tuHmAdnofqs72w4mKYNy4R9fhs5+OlhnhgylPwAVz5/yC6Vnr9g9NIRvNnKXjybGal0cNj9H4JLFmDAkAhw5lggAUm+TQHOHkDqvybZtFQT5zvaQvfQASDrtv7vA4xY2CT2FULsCtczsCOBcNU47edJJZ9vFK9FiMuSWQmBb5xh25Gcv6YnWlQSiQSmRlWg/504v50thEAQmM2DI8zYn+jWBTZwig003oYji0taUySsen+wvDX/h+/+VNh1KNFL7YmorO2pGmzzzmrr6012MdGxhvnEWx1TYgasS5SNtiIkcRwF7E6nQFAJqvg4YVPx+BCxV5Hy54uV7JJOVrTh75YhpZ/Y=
  - secure: Jqpk+1SZiXMq42n4msfHpd+GBIY6PD+DcAv/t8HAeQk27kSjRGybh/nskXQ4uO76PNfAVc0isiQK1+TDgJKP7Mv3zJl++XpXKFL/75sWLo9uDcEz/JZEjahhbPtbn9MeLSJXa70TngcRiRIdb89rc7jH7ZNwzwnN27IuZlZ6NUDLe0sWBg26RfP5MTojZTkuDKS7zmeYACG93uMWJqiNYnoZ/xH3mRySmDIwHIfsPOGpeWKwVVAVUCpP7VoTP+MiIzlblxLk7BTu8Jyh6F3TcrWFAcZaRAk15jxs3UvWZ60xS3HhGsLBuVVnnVIVRNeBovtpsq+cU5dz27C4MKMZI3dpB3F3IgsqHo1Ru4giYeqEvdRQIlDhL+2RQCUE+FyHltheqvAhLwvSuV8EybG4Eyqu73C3vUhQ0/WPzCtJQcqA5pmsvMskbhk/5lsUW/eg/fMTxcsqp5AW3ADRmmC+CG8ep2A7W0zg1rdeZgbdIXVH4Xj7uKRaDWqpMNM1MTxDuT4iTWCkci4ncnLRufhXglcBDHD9rwlPskyKv2QNXepRtDqFMoM9krLQ/k2A9LcWXcCKWC5mq/DahJR03QQLJ7uXK3si2GMYriwoLQwIjaXUAiPmVa3ZHuE5HjDbw7yXlhEzbM3xdIPANDZs69T5+/as1Dkfx/r2KcD1Uaj1v60=
script:
- bash travis-build.sh
