---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shakespeare
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shakespeare
    spec:
      containers:
      - name: shakespeare
        image: reveller/shakespeare:1.3
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 5000
